import turtle
sally = turtle.Turtle()

sally.shape('turtle')
sally.color('purple')
sally.speed('fastest')
sally.penup()
sally.setposition(0, -50)

sally.pencolor('green')
sally.width(14)
sally.pendown()
sally.circle(100) #turtle shell #100 is the radius

sally.penup()
sally.setposition(-20, 150)
sally.pendown()
sally.forward(40)
sally.left(75)
sally.forward(50)
sally.left(70)
sally.forward(45)
sally.left(70)
sally.forward(40)
sally.left(75)
sally.forward(50)

sally.penup()
sally.setposition(55, -26)
sally.pendown()
sally.forward(40)
sally.left(75)
sally.forward(25)
sally.left(40)
sally.forward(25)
sally.left(90)
sally.forward(40)

sally.penup()
sally.setposition(90, 67)
sally.pendown()
sally.right(90)
sally.forward(45)
sally.left(45)
sally.forward(25)
sally.left(45)
sally.forward(25)
sally.left(65)
sally.forward(45)

sally.penup()
sally.setposition(-110, 67)
sally.pendown()
sally.right(45)
sally.forward(30)
sally.right(40)
sally.forward(30)
sally.right(40)
sally.forward(20)
sally.right(85)
sally.forward(55)

sally.penup()
sally.setposition(-95, -5)
sally.pendown()
sally.left(205)
sally.forward(30)
sally.left(40)
sally.forward(20)
sally.left(20)
sally.forward(20)
sally.left(105)
sally.forward(40)
sally.left(40)
sally.forward(40)

turtle.done()
